import io
from typing import Dict, Any
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, KeepTogether
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.pdfgen import canvas

class NumberedCanvas(canvas.Canvas):
    """
    A canvas that enables dynamic two-pass page numbering
    (e.g., 'Page X of Y') along with headers and footers.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count):
        self.saveState()
        
        # Suppress header/footer on page 1 if it's a cover-like start page, 
        # but for this roadmap, a unified professional top/bottom bar is clean.
        
        # Primary Color: Deep Slate/Blue
        # Text/Line Color: Slate gray (60% gray)
        self.setFont("Helvetica-Bold", 8)
        self.setFillColor(colors.HexColor("#475569"))
        self.drawString(54, 755, "SKILLPATH AI")
        
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#64748b"))
        self.drawRightString(558, 755, "Personalized Learning Roadmap")
        
        # Header Line
        self.setStrokeColor(colors.HexColor("#cbd5e1"))
        self.setLineWidth(0.5)
        self.line(54, 747, 558, 747)
        
        # Footer Line
        self.line(54, 48, 558, 48)
        
        # Footer Text
        self.drawString(54, 35, "Generated by SkillPath AI - Your AI-powered Guide")
        page_text = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(558, 35, page_text)
        
        self.restoreState()


def generate_roadmap_pdf(roadmap: Dict[str, Any]) -> io.BytesIO:
    """
    Generates a professional styled PDF document from a roadmap dictionary.
    Returns a BytesIO stream containing the PDF data.
    """
    buffer = io.BytesIO()
    
    # Document dimensions (Letter: 612 x 792 pt).
    # Margins: Left=54, Right=54, Top=72 (leaves space for header), Bottom=72 (leaves space for footer).
    # Content width: 612 - 108 = 504 pt.
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=54,
        rightMargin=54,
        topMargin=72,
        bottomMargin=72
    )
    
    styles = getSampleStyleSheet()
    
    # Define custom color palette
    primary_color = colors.HexColor("#1e293b")  # Slate 800
    accent_color = colors.HexColor("#4f46e5")   # Indigo 600
    text_color = colors.HexColor("#334155")     # Slate 700
    light_bg = colors.HexColor("#f8fafc")       # Slate 50
    border_color = colors.HexColor("#e2e8f0")   # Slate 200
    
    # Custom Paragraph Styles
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=24,
        leading=28,
        textColor=primary_color,
        spaceAfter=6
    )
    
    subtitle_style = ParagraphStyle(
        'DocSubtitle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=12,
        leading=16,
        textColor=accent_color,
        spaceAfter=15
    )
    
    meta_label_style = ParagraphStyle(
        'MetaLabel',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=10,
        leading=14,
        textColor=primary_color
    )
    
    meta_val_style = ParagraphStyle(
        'MetaValue',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10,
        leading=14,
        textColor=text_color
    )
    
    phase_title_style = ParagraphStyle(
        'PhaseTitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=14,
        leading=18,
        textColor=colors.white
    )
    
    section_heading_style = ParagraphStyle(
        'SectionHeading',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=12,
        leading=16,
        textColor=primary_color,
        spaceBefore=12,
        spaceAfter=6
    )
    
    body_style = ParagraphStyle(
        'BodyTextCustom',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9.5,
        leading=13.5,
        textColor=text_color
    )
    
    table_header_style = ParagraphStyle(
        'TableHeader',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=9.5,
        leading=13,
        textColor=primary_color
    )
    
    bullet_style = ParagraphStyle(
        'BulletCustom',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9,
        leading=13,
        textColor=text_color,
        leftIndent=15,
        firstLineIndent=-10,
        spaceBefore=2
    )

    story = []
    
    # ------------------ TITLE SECTION ------------------
    story.append(Spacer(1, 10))
    story.append(Paragraph(f"SkillPath: {roadmap.get('skill_name', 'Learning Roadmap')}", title_style))
    story.append(Paragraph("Your Custom AI-Generated Mastery Guide", subtitle_style))
    
    # ------------------ SUMMARY METADATA BLOCK ------------------
    summary_data = [
        [
            Paragraph("Estimated Duration:", meta_label_style),
            Paragraph(roadmap.get('estimated_duration', 'N/A'), meta_val_style),
            Paragraph("Daily Study Time:", meta_label_style),
            Paragraph(roadmap.get('daily_study_time', 'N/A'), meta_val_style)
        ],
        [
            Paragraph("Final Outcome:", meta_label_style),
            Paragraph(roadmap.get('final_outcome', 'N/A'), meta_val_style),
            "", "" # Spanning cells
        ]
    ]
    
    # 504 total width: Col widths = 110, 142, 110, 142
    summary_table = Table(summary_data, colWidths=[110, 142, 110, 142])
    summary_table.setStyle(TableStyle([
        ('SPAN', (1, 1), (3, 1)), # Span final outcome across three columns
        ('BACKGROUND', (0, 0), (-1, -1), light_bg),
        ('BOX', (0, 0), (-1, -1), 1, border_color),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, border_color),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('LEFTPADDING', (0, 0), (-1, -1), 10),
        ('RIGHTPADDING', (0, 0), (-1, -1), 10),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
    ]))
    
    story.append(summary_table)
    story.append(Spacer(1, 20))
    
    # ------------------ PHASES ------------------
    phases = roadmap.get('phases', [])
    for idx, phase in enumerate(phases):
        phase_elements = []
        
        phase_num = phase.get('phase_number', idx + 1)
        phase_title = phase.get('title', f"Phase {phase_num}")
        
        # 1. Phase Header Bar
        header_data = [[Paragraph(f"PHASE {phase_num}: {phase_title.upper()}", phase_title_style)]]
        header_table = Table(header_data, colWidths=[504])
        header_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), accent_color),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
            ('LEFTPADDING', (0, 0), (-1, -1), 10),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ]))
        phase_elements.append(header_table)
        phase_elements.append(Spacer(1, 8))
        
        # 2. Practice Schedule Label
        practice_text = f"<b>Recommended Practice:</b> {phase.get('practice_schedule', 'N/A')}"
        phase_elements.append(Paragraph(practice_text, body_style))
        phase_elements.append(Spacer(1, 8))
        
        # 3. Topics Table
        topics = phase.get('topics', [])
        if topics:
            topics_data = [[Paragraph("Topic", table_header_style), Paragraph("Detailed Subtopics", table_header_style)]]
            for topic in topics:
                t_name = topic.get('name', '')
                t_subs = ", ".join(topic.get('subtopics', []))
                topics_data.append([
                    Paragraph(f"<b>{t_name}</b>", body_style),
                    Paragraph(t_subs, body_style)
                ])
            
            # Widths: Topic = 140, Subtopics = 364
            topics_table = Table(topics_data, colWidths=[140, 364])
            topics_table_style = [
                ('BACKGROUND', (0, 0), (-1, 0), border_color),
                ('BOX', (0, 0), (-1, -1), 0.75, border_color),
                ('INNERGRID', (0, 0), (-1, -1), 0.5, border_color),
                ('TOPPADDING', (0, 0), (-1, -1), 6),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
                ('LEFTPADDING', (0, 0), (-1, -1), 8),
                ('RIGHTPADDING', (0, 0), (-1, -1), 8),
                ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ]
            
            # Alternating row background
            for r_idx in range(1, len(topics_data)):
                if r_idx % 2 == 0:
                    topics_table_style.append(('BACKGROUND', (0, r_idx), (-1, r_idx), light_bg))
                    
            topics_table.setStyle(TableStyle(topics_table_style))
            phase_elements.append(topics_table)
            phase_elements.append(Spacer(1, 10))
            
        # 4. Projects Box
        mini_proj = phase.get('mini_project', {})
        major_proj = phase.get('major_project')
        
        if mini_proj or major_proj:
            phase_elements.append(Paragraph("Hands-on Projects", section_heading_style))
            
            proj_story = []
            if mini_proj:
                p_title = mini_proj.get('title', 'Mini Project')
                p_desc = mini_proj.get('description', '')
                p_skills = ", ".join(mini_proj.get('skills_used', []))
                
                proj_story.append(Paragraph(f"<b>Mini Project: {p_title}</b>", body_style))
                proj_story.append(Paragraph(p_desc, body_style))
                if p_skills:
                    proj_story.append(Paragraph(f"<i>Skills practiced: {p_skills}</i>", body_style))
                    
            if major_proj:
                if mini_proj:
                    proj_story.append(Spacer(1, 6))
                mp_title = major_proj.get('title', 'Major Capstone')
                mp_desc = major_proj.get('description', '')
                mp_skills = ", ".join(major_proj.get('skills_used', []))
                
                proj_story.append(Paragraph(f"<b>Major Capstone Project: {mp_title}</b>", body_style))
                proj_story.append(Paragraph(mp_desc, body_style))
                if mp_skills:
                    proj_story.append(Paragraph(f"<i>Skills practiced: {mp_skills}</i>", body_style))
            
            # Put projects in a border box
            proj_cell = [[proj_story]]
            proj_table = Table(proj_cell, colWidths=[504])
            proj_table.setStyle(TableStyle([
                ('BOX', (0, 0), (-1, -1), 0.75, border_color),
                ('BACKGROUND', (0, 0), (-1, -1), light_bg),
                ('TOPPADDING', (0, 0), (-1, -1), 8),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
                ('LEFTPADDING', (0, 0), (-1, -1), 10),
                ('RIGHTPADDING', (0, 0), (-1, -1), 10),
            ]))
            phase_elements.append(proj_table)
            phase_elements.append(Spacer(1, 10))
            
        # 5. Milestones
        milestones = phase.get('milestones', [])
        if milestones:
            phase_elements.append(Paragraph("Phase Milestones", section_heading_style))
            for ms in milestones:
                phase_elements.append(Paragraph(f"&bull; {ms}", bullet_style))
            phase_elements.append(Spacer(1, 10))
            
        # Force a page break between phases, except after the last one
        if idx < len(phases) - 1:
            # We want each phase to stay cohesive and start on its own page
            # KeepTogether ensures the phase content doesn't break internally unless needed,
            # but since it's a full page anyway, we just append content and end with PageBreak.
            story.extend(phase_elements)
            story.append(PageBreak())
        else:
            story.extend(phase_elements)

    # Build PDF
    doc.build(story, canvasmaker=NumberedCanvas)
    buffer.seek(0)
    return buffer
